eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8070

spring:
  application:
    name: schools
  datasource:
    url: jdbc:mysql://localhost:3306/schools
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    database: mysql

application:
  config:
    student-url: http://localhost:8222/api/v1/students